version: "3.8"

services:
  auth-service:
    build: .
    container_name: notes-auth-micro
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - notes-network
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/notes-users

  mongodb:
    image: mongo:6.0
    container_name: notes-users-mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge

volumes:
  mongodb_data:
